### ISSUE TITLE
Quiz Feedback

### ISSUE THREAD

**Issue by udiiin** [rahadi23/hsi-sandbox-lvl-2#1]
Barokallaah, udah mantab banget mas 👍 

- Secara functional udah oke ✅
- Styling udah oke ✅
- Penggunaan custom hook oke ✅
- Ada tambahan prop-types nya ✅

Saya ada sedikit feedback aja:

1.)  
Validasi nomor hape: _no hp harus diawali dengan “08” dan **jumlah angka selanjutnya** minimal 8 dan maksimal 12_.  
Artinya utk keseluruhan jumlah angka itu minimal 10 & maksimal 14

2.)  
Line 550: `const { getInputProps, validate, values, isValid, setValue } = useForm({`,  
`isValid` gak ada di dalam returnnya `useForm`

**Comment by aditiopangestu** [comment]
setuju dengan mas @udiiin, untuk source code sudah rapi, ada feedback tambahan juga dari saya untuk penggunaan `useMemo` di kasus ini kurang tepat detailnya bisa cek di https://react.dev/reference/react/useMemo

**Comment by rahadi23** [comment]
terima kasih atas issue dan reviewnya Mas @udiiin dan Mas @aditiopangestu 

untuk feedback yang diberikan sudah saya perbaiki sebagai berikut:

> Validasi nomor hape: no hp harus diawali dengan “08” dan jumlah angka selanjutnya minimal 8 dan maksimal 12.
Artinya utk keseluruhan jumlah angka itu minimal 10 & maksimal 14

sudah saya perbaiki dengan mengubah rule validasi sebelumnya menjadi regex sebagai berikut:

https://github.com/rahadi23/hsi-sandbox-lvl-2/blob/b4df44033879ae0b3f5698937a54f356af320e5e/index.html#L596-L598

untuk detail perubahannya bisa dilihat di dbeec85.

> Line 550: `const { getInputProps, validate, values, isValid, setValue } = useForm({`, `isValid` gak ada di dalam returnnya `useForm`

untuk issue ini kemarin karena rencana memang saya return, tetapi tidak jadi menggunakan cara itu tapi lupa menghapus returnnya. sudah saya hapus karena memang tidak digunakan. cara yang jadinya saya pakai adalah mereturn nilai `isValid` saat memanggil fungsi `validate()`. bisa dilihat di line berikut:

https://github.com/rahadi23/hsi-sandbox-lvl-2/blob/b4df44033879ae0b3f5698937a54f356af320e5e/index.html#L627-L632

untuk detail perubahannya bisa dilihat di 5a7165e.

> untuk penggunaan `useMemo` di kasus ini kurang tepat

ini awalnya saya bermaksud untuk merender form dengan condition sesuai stepnya, namun setelah saya pelajari lebih jauh memang sepertinya kurang tepat menggunakan `useMemo`. jadi saya perbaiki dengan mengubah renderingnya menjadi function biasa saja sebagai berikut:

https://github.com/rahadi23/hsi-sandbox-lvl-2/blob/b4df44033879ae0b3f5698937a54f356af320e5e/index.html#L634-L659

https://github.com/rahadi23/hsi-sandbox-lvl-2/blob/b4df44033879ae0b3f5698937a54f356af320e5e/index.html#L665-L669

untuk detail perubahannya bisa dilihat di 8c22cc2.

setelah perbaikan, berikut adalah demo videonya. video juga akan saya kirimkan ke channel discord

https://user-images.githubusercontent.com/18496523/236364719-7d11f9c0-2fed-46df-a3b2-17b30fe5d809.mp4

sekian, sekali lagi saya ucapkan terima kasih atas reviewnya Mas. Jazakumullahu khair.

**Comment by udiiin** [comment]
Mantab mas ✨ 

Dari aku udah oke sih...  
Jazaakallaahu khoir

**Comment by aditiopangestu** [comment]
sama dari aku sudah ok, baarakallahu fiik
